title: Your Title
description: > # this means to ignore newlines until "baseurl:"
  Your description
baseurl: "" # the subpath of your site, e.g. /blog
url: "Your-Link.github.io" # the base hostname & protocol for your site

organization: My Organization
organization_url: https://www.myorg.com
support_team: This Team
support_team_email: ouremail@example.com

#this amount different from GMT, so use this to determine current time
timezone_adjustment: 18000

# Build settings
logo: "/img/icon-large.png"

include: ['_plugins']

collections:
  speakers:
    sort_by: username
  topics:


plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Build settings
markdown: kramdown
permalink: pretty

sass:
  sass_dir: _sass
  style: compressed

